# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/yanha/Desktop/Vivado project/project_1_2_mux2x1/project_1_2_mux2x1.srcs/sources_1/bd/mux2x1_1/ip/mux2x1_1_orgate_0_0/mux2x1_1_orgate_0_0.xci
# IP: The module: 'mux2x1_1_orgate_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yanha/Desktop/Vivado project/project_1_2_mux2x1/Users/yanha/Desktop/Vivado project/project_1_orgate/project_1_orgate.srcs/constrs_1/new/orgate_xdc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mux2x1_1_orgate_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/yanha/Desktop/Vivado project/project_1_2_mux2x1/project_1_2_mux2x1.srcs/sources_1/bd/mux2x1_1/ip/mux2x1_1_orgate_0_0/mux2x1_1_orgate_0_0.xci
# IP: The module: 'mux2x1_1_orgate_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yanha/Desktop/Vivado project/project_1_2_mux2x1/Users/yanha/Desktop/Vivado project/project_1_orgate/project_1_orgate.srcs/constrs_1/new/orgate_xdc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mux2x1_1_orgate_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
