set_property IOSTANDARD LVCMOS33 [get_ports in1]
set_property IOSTANDARD LVCMOS33 [get_ports in2]
set_property IOSTANDARD LVCMOS33 [get_ports out1]
set_property IOSTANDARD LVCMOS33 [get_ports out2]
set_property PACKAGE_PIN R2 [get_ports in1]
set_property PACKAGE_PIN T1 [get_ports in2]
set_property PACKAGE_PIN E19 [get_ports out1]
set_property PACKAGE_PIN U16 [get_ports out2]
