# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/mux2x1.xdc

# Block Designs: bd/mux2x1_1/mux2x1_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mux2x1_1 || ORIG_REF_NAME==mux2x1_1} -quiet] -quiet

# IP: bd/mux2x1_1/ip/mux2x1_1_andgate_0_0/mux2x1_1_andgate_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mux2x1_1_andgate_0_0 || ORIG_REF_NAME==mux2x1_1_andgate_0_0} -quiet] -quiet

# IP: bd/mux2x1_1/ip/mux2x1_1_andgate_1_0/mux2x1_1_andgate_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mux2x1_1_andgate_1_0 || ORIG_REF_NAME==mux2x1_1_andgate_1_0} -quiet] -quiet

# IP: bd/mux2x1_1/ip/mux2x1_1_orgate_0_0/mux2x1_1_orgate_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mux2x1_1_orgate_0_0 || ORIG_REF_NAME==mux2x1_1_orgate_0_0} -quiet] -quiet

# IP: bd/mux2x1_1/ip/mux2x1_1_notgate_0_0/mux2x1_1_notgate_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mux2x1_1_notgate_0_0 || ORIG_REF_NAME==mux2x1_1_notgate_0_0} -quiet] -quiet

# XDC: bd/mux2x1_1/mux2x1_1_ooc.xdc
