set_property SRC_FILE_INFO {cfile:{C:/Users/yanha/Desktop/Vivado project/project_1_2_mux2x1/project_1_2_mux2x1.srcs/constrs_1/new/mux2x1.xdc} rfile:../../../project_1_2_mux2x1.srcs/constrs_1/new/mux2x1.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {f[0]}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R2 [get_ports a]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T1 [get_ports b]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U1 [get_ports s]
