# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/yanha/Desktop/Vivado project/project_1_3_mux4x1.block_design/project_1_3_mux4x1.block_design.srcs/sources_1/bd/mux4x1_block/ip/mux4x1_block_orgate_2_0/mux4x1_block_orgate_2_0.xci
# IP: The module: 'mux4x1_block_orgate_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yanha/Desktop/Vivado project/project_1_3_mux4x1.block_design/Users/yanha/Desktop/Vivado project/project_1_orgate/project_1_orgate.srcs/constrs_1/new/orgate_xdc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mux4x1_block_orgate_2_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/yanha/Desktop/Vivado project/project_1_3_mux4x1.block_design/project_1_3_mux4x1.block_design.srcs/sources_1/bd/mux4x1_block/ip/mux4x1_block_orgate_2_0/mux4x1_block_orgate_2_0.xci
# IP: The module: 'mux4x1_block_orgate_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yanha/Desktop/Vivado project/project_1_3_mux4x1.block_design/Users/yanha/Desktop/Vivado project/project_1_orgate/project_1_orgate.srcs/constrs_1/new/orgate_xdc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mux4x1_block_orgate_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
