# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/mux4x1_block_de_xdc.xdc

# Block Designs: bd/mux4x1_block/mux4x1_block.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mux4x1_block || ORIG_REF_NAME==mux4x1_block} -quiet] -quiet

# IP: bd/mux4x1_block/ip/mux4x1_block_notgate_2_0_0/mux4x1_block_notgate_2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mux4x1_block_notgate_2_0_0 || ORIG_REF_NAME==mux4x1_block_notgate_2_0_0} -quiet] -quiet

# IP: bd/mux4x1_block/ip/mux4x1_block_andgate_0_0/mux4x1_block_andgate_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mux4x1_block_andgate_0_0 || ORIG_REF_NAME==mux4x1_block_andgate_0_0} -quiet] -quiet

# IP: bd/mux4x1_block/ip/mux4x1_block_andgate_1_0/mux4x1_block_andgate_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mux4x1_block_andgate_1_0 || ORIG_REF_NAME==mux4x1_block_andgate_1_0} -quiet] -quiet

# IP: bd/mux4x1_block/ip/mux4x1_block_andgate_2_0/mux4x1_block_andgate_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mux4x1_block_andgate_2_0 || ORIG_REF_NAME==mux4x1_block_andgate_2_0} -quiet] -quiet

# IP: bd/mux4x1_block/ip/mux4x1_block_andgate_3_0/mux4x1_block_andgate_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mux4x1_block_andgate_3_0 || ORIG_REF_NAME==mux4x1_block_andgate_3_0} -quiet] -quiet

# IP: bd/mux4x1_block/ip/mux4x1_block_orgate_0_0/mux4x1_block_orgate_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mux4x1_block_orgate_0_0 || ORIG_REF_NAME==mux4x1_block_orgate_0_0} -quiet] -quiet

# IP: bd/mux4x1_block/ip/mux4x1_block_orgate_1_0/mux4x1_block_orgate_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mux4x1_block_orgate_1_0 || ORIG_REF_NAME==mux4x1_block_orgate_1_0} -quiet] -quiet

# IP: bd/mux4x1_block/ip/mux4x1_block_andgate_4_0/mux4x1_block_andgate_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mux4x1_block_andgate_4_0 || ORIG_REF_NAME==mux4x1_block_andgate_4_0} -quiet] -quiet

# IP: bd/mux4x1_block/ip/mux4x1_block_andgate_5_0/mux4x1_block_andgate_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mux4x1_block_andgate_5_0 || ORIG_REF_NAME==mux4x1_block_andgate_5_0} -quiet] -quiet

# IP: bd/mux4x1_block/ip/mux4x1_block_andgate_6_0/mux4x1_block_andgate_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mux4x1_block_andgate_6_0 || ORIG_REF_NAME==mux4x1_block_andgate_6_0} -quiet] -quiet

# IP: bd/mux4x1_block/ip/mux4x1_block_andgate_7_0/mux4x1_block_andgate_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mux4x1_block_andgate_7_0 || ORIG_REF_NAME==mux4x1_block_andgate_7_0} -quiet] -quiet

# IP: bd/mux4x1_block/ip/mux4x1_block_andgate_8_0/mux4x1_block_andgate_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mux4x1_block_andgate_8_0 || ORIG_REF_NAME==mux4x1_block_andgate_8_0} -quiet] -quiet

# IP: bd/mux4x1_block/ip/mux4x1_block_andgate_9_0/mux4x1_block_andgate_9_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mux4x1_block_andgate_9_0 || ORIG_REF_NAME==mux4x1_block_andgate_9_0} -quiet] -quiet

# IP: bd/mux4x1_block/ip/mux4x1_block_andgate_10_0/mux4x1_block_andgate_10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mux4x1_block_andgate_10_0 || ORIG_REF_NAME==mux4x1_block_andgate_10_0} -quiet] -quiet

# IP: bd/mux4x1_block/ip/mux4x1_block_andgate_11_0/mux4x1_block_andgate_11_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mux4x1_block_andgate_11_0 || ORIG_REF_NAME==mux4x1_block_andgate_11_0} -quiet] -quiet

# IP: bd/mux4x1_block/ip/mux4x1_block_orgate_2_0/mux4x1_block_orgate_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mux4x1_block_orgate_2_0 || ORIG_REF_NAME==mux4x1_block_orgate_2_0} -quiet] -quiet

# XDC: bd/mux4x1_block/mux4x1_block_ooc.xdc
